### ISSUE TITLE
Add captions to images 

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/digital-garden#40]
The images come with captions, find a way to add them to the image

**Comment by Ryuno-Ki** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption perhaps?

**Comment by inezabonte** [comment]
Thanks @Ryuno-Ki. That was the push I needed. I knew it was along the lines of the figure element but couldn't bring myself to do it.

**Comment by inezabonte** [comment]
@Ryuno-Ki you can check the gallery out here https://garden.ineza.codes/gallery.
